Repository kanidm/kanidm, pull requests merged in 2022-05, with the labels that each got.

#737 Orca output dir fix
  Cargo.lock
  kanidmd/daemon/run_insecure_dev_server.sh
  orca/Cargo.toml
  orca/src/opt.rs
  orca/src/runner/mod.rs
Labels: uwu

#738 Orca files
  orca/src/opt.rs
Labels: uwu

#741 Dockerized containerybuilds
  .github/workflows/docker_build.yml
  .github/workflows/docker_images.yml.disabled
  kanidm_rlm_python/Dockerfile
  kanidmd/Dockerfile
Labels: automation

#749 Ok dependabot I will do the thing 2022-05-09
  .github/dependabot.yml
  Cargo.lock
  kanidm_proto/src/v1.rs
Labels: dependencies, rust, automation

#754 Update issue templates
  .github/ISSUE_TEMPLATE/an-idea-or-question.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/security_report.md
Labels: uwu

#751 fixing up typo and tagging on docker build
  .github/workflows/docker_build.yml
Labels: bug, automation

#773 Improve token readability, Fix issue with spn format
  kanidm_book/src/pam_and_nsswitch.md
  kanidmd/Dockerfile
  kanidmd/idm/src/actors/v1_write.rs
  kanidmd/idm/src/be/dbentry.rs
  kanidmd/idm/src/be/dbvalue.rs
  kanidmd/idm/src/be/idl_sqlite.rs
  kanidmd/idm/src/be/mod.rs
  kanidmd/idm/src/constants/mod.rs
  kanidmd/idm/src/constants/schema.rs
  kanidmd/idm/src/entry.rs
  kanidmd/idm/src/idm/account.rs
  kanidmd/idm/src/idm/credupdatesession.rs
  kanidmd/idm/src/server.rs
  kanidmd/idm/src/value.rs
  kanidmd/idm/src/valueset/cred.rs
  kanidmd/idm/src/valueset/mod.rs
Labels: bug

#779 Yak shaving 2343443
  .github/dependabot.yml
  check_dependabot.sh
  kanidmd/score/tests/common.rs
  kanidmd/score/tests/https_middleware.rs
Labels: uwu

#790 Moving an info message because that's how I roll
  Cargo.lock
  kanidmd/score/src/https/mod.rs
Labels: uwu

#791 Updating developer readme to mention devel containers.
  DEVELOPER_README.md
Labels: uwu

#798 Windows automagical buildingtons
  .github/workflows/docker_build.yml
  .github/workflows/windows_build.yml
  kanidm_book/src/installing_client_tools.md
  kanidm_client/src/lib.rs
  kanidmd/Dockerfile
  kanidmd/daemon/Cargo.toml
  kanidmd/daemon/src/main.rs
  kanidmd/idm/src/lib.rs
  kanidmd/score/src/https/mod.rs
  orca/Cargo.toml
  orca/src/main.rs
Labels: enhancement, automation
