Repository kanidm/kanidm, pull requests merged in 2022-06, with the labels that each got.

#799 updated docs for ubuntu notes
  DEVELOPER_README.md
Labels: documentation

#800 Kanidm book review 6
  kanidm_book/src/client_tools.md
  kanidm_book/src/ldap.md
  kanidm_book/src/pam_and_nsswitch.md
  kanidm_book/src/radius.md
Labels: documentation

#807 updates the OAUTH2 service_documentation URL, updating book layout
  kanidm_book/src/SUMMARY.md
  kanidm_book/src/integrations/ldap.md
  kanidm_book/src/integrations/oauth2.md
  kanidm_book/src/integrations/pam_and_nsswitch.md
  kanidm_book/src/integrations/radius.md
  kanidmd/idm/src/idm/oauth2.rs
Labels: bug, documentation

#811 Updating build profiles for containers
  .github/workflows/docker_build.yml
  Makefile
Labels: bug, automation

#805 K8s Ingress Example
  kanidm_book/src/SUMMARY.md
  kanidm_book/src/examples/k8s_ingress_example.md
Labels: documentation

#819 adding new favicon and square logo, updating build scripts
  artwork/favicon.svg
  artwork/logo-square.svg
  kanidmd/score/src/https/mod.rs
  kanidmd_web_ui/build_wasm_dev.sh
  kanidmd_web_ui/build_wasm_release.sh
  kanidmd_web_ui/pkg/img/favicon.png
  kanidmd_web_ui/pkg/img/logo-square.svg
  kanidmd_web_ui/pkg/kanidmd_web_ui.js
  kanidmd_web_ui/pkg/style.css
  kanidmd_web_ui/src/favicon.svg
  kanidmd_web_ui/src/img/favicon.png
  kanidmd_web_ui/src/img/logo-square.svg
  kanidmd_web_ui/src/login.rs
  kanidmd_web_ui/src/style.css
Labels: uwu

#855 Showing the TOTP URI to the user when doing a TOTP cred reset
  kanidm_client/src/lib.rs
  kanidm_tools/src/cli/account.rs
Labels: enhancement, uwu

#856 moving pull request template
  .github/pull_request_template.md
Labels: uwu

#854 Adding hazard-kani to artwork
  artwork/kani-hazard.png
  artwork/logo.svg
Labels: uwu

#858 updated docs to include more required packages for ubuntu
  DEVELOPER_README.md
Labels: documentation
