Repository kanidm/kanidm, pull requests merged in 2023-09, with the labels that each got.

#2072 docs: api tokens are managed by idm_admin
  book/src/accounts_and_groups.md
Labels: documentation

#2059 Yak hassling
  .gitignore
  server/core/src/https/v1.rs
  server/daemon/src/main.rs
  server/lib/Cargo.toml
  server/lib/src/be/idl_arc_sqlite.rs
  server/lib/src/be/idl_sqlite.rs
  server/lib/src/be/mod.rs
  server/lib/src/server/mod.rs
  server/web_ui/build_wasm.sh
  server/web_ui/src/views/mod.rs
Labels: uwu, internals, kanidmd

#2071 Schema dooby doo part two
  proto/src/constants.rs
  proto/src/scim_v1.rs
  server/core/src/https/v1.rs
  server/lib/src/be/dbentry.rs
  server/lib/src/be/mod.rs
  server/lib/src/constants/entries.rs
  server/lib/src/entry.rs
  server/lib/src/filter.rs
  server/lib/src/idm/account.rs
  server/lib/src/idm/credupdatesession.rs
  server/lib/src/idm/ldap.rs
  server/lib/src/idm/oauth2.rs
  server/lib/src/idm/scim.rs
  server/lib/src/idm/server.rs
  server/lib/src/idm/serviceaccount.rs
  server/lib/src/modify.rs
  server/lib/src/plugins/attrunique.rs
  server/lib/src/plugins/base.rs
  server/lib/src/plugins/cred_import.rs
  server/lib/src/plugins/dyngroup.rs
  server/lib/src/plugins/jwskeygen.rs
  server/lib/src/plugins/memberof.rs
  server/lib/src/plugins/protected.rs
  server/lib/src/plugins/refint.rs
  server/lib/src/repl/supplier.rs
  server/lib/src/repl/tests.rs
  server/lib/src/schema.rs
  server/lib/src/server/access/mod.rs
  server/lib/src/server/delete.rs
  server/lib/src/server/migrations.rs
  server/lib/src/server/mod.rs
  server/lib/src/server/modify.rs
  server/lib/src/server/recycle.rs
  server/lib/src/value.rs
  server/testkit/tests/default_entries.rs
  server/testkit/tests/https_extractors.rs
Labels: internals

#2078 Removing default features from git2 package
  Cargo.lock
  Cargo.toml
  server/lib/src/plugins/refint.rs
  server/lib/src/repl/tests.rs
Labels: uwu

#2076 Changing build targets for debs
  .github/workflows/clippy.yml
  .github/workflows/codespell.yml
  .github/workflows/debian_package_kanidm.yml
  .github/workflows/dependabot_auto_merge.yml
  .github/workflows/dependency_review.yml
  .github/workflows/docker_build_kanidm.yml
  .github/workflows/docker_build_kanidmd.yml
  .github/workflows/docker_build_radiusd.yml
  .github/workflows/kanidm_book.yml
  .github/workflows/kanidm_individual_book.yml
  .github/workflows/pykanidm.yml
  .github/workflows/rust_build.yml
  .github/workflows/wasm_test.yml
  .github/workflows/windows_build.yml
Labels: automation, github_actions

#2080 CLI and test things
  .github/workflows/rust_build.yml
  Cargo.lock
  scripts/setup_dev_environment.sh
  scripts/test_run_release_server.sh
  server/lib/src/be/idl_arc_sqlite.rs
  tools/cli/Cargo.toml
  tools/cli/src/cli/badlist.rs
  tools/cli/src/cli/domain.rs
  tools/cli/src/cli/group.rs
  tools/cli/src/cli/lib.rs
  tools/cli/src/cli/oauth2.rs
  tools/cli/src/cli/person.rs
  tools/cli/src/cli/recycle.rs
  tools/cli/src/cli/serviceaccount.rs
  tools/cli/src/cli/session_expiry.rs
  tools/cli/src/cli/synch.rs
  tools/cli/src/ssh_authorizedkeys.rs
Labels: uwu, automation, kanidm (cli)

#2082 Schema-dooby-doo-part-trois
  libs/sketching/src/lib.rs
  server/lib/src/constants/acp.rs
  server/lib/src/constants/entries.rs
  server/lib/src/event.rs
  server/lib/src/idm/account.rs
  server/lib/src/idm/authsession.rs
  server/lib/src/macros.rs
  server/lib/src/repl/tests.rs
  server/lib/src/server/migrations.rs
  server/lib/src/server/modify.rs
Labels: uwu, internals

#2085 move from git2 to gix
  Cargo.lock
  Cargo.toml
  libs/profiles/Cargo.toml
  libs/profiles/build.rs
Labels: uwu, dependencies

#2104 sqlite3 doesn't need to be installed on dev machines
  .github/workflows/clippy.yml
  .github/workflows/kanidm_individual_book.yml
  .github/workflows/rust_build.yml
  Cargo.toml
  book/src/DEVELOPER_README.md
  platform/debian/install_deps.sh
  platform/debian/kanidm-unixd/control
  platform/debian/kanidm/control
  platform/debian/kanidmd/control
  scripts/install_ubuntu_dependencies.sh
Labels: dependencies

#2127 CLI and kanidm_client changes to handle errors and TLS validation changes
  Cargo.lock
  libs/client/Cargo.toml
  libs/client/src/lib.rs
  tools/cli/Cargo.toml
  tools/cli/src/cli/common.rs
  tools/cli/src/cli/lib.rs
  tools/cli/src/opt/kanidm.rs
Labels: uwu, kanidm (cli)

#2133 Minor CI change to speed up WASM tests
  .github/workflows/wasm_test.yml
Labels: automation

#2145 Enforce TLS key size minimums
  Cargo.lock
  Cargo.toml
  book/src/security_hardening.md
  libs/profiles/Cargo.toml
  server/core/Cargo.toml
  server/core/src/crypto.rs
  server/core/src/ldaps.rs
  server/core/src/lib.rs
  server/lib/src/server/access/search.rs
  server/testkit-macros/Cargo.toml
Labels: enhancement, security

#2154 Can't build kanidmd using the Ubuntu docker builder scripts
  book/src/packaging_debs.md
  platform/debian/build_kanidm.sh
  platform/debian/fix_wasm_opt.sh
  platform/debian/install_deps.sh
  platform/debian/kanidmd/rules
  platform/debian/ubuntu_docker_builder.sh
  scripts/install_ubuntu_dependencies.sh
Labels: automation, documentation
