Repository kanidm/kanidm, pull requests merged in 2023-08, with the labels that each got.

#1941 Allow one-character usernames
  server/lib/src/value.rs
Labels: enhancement, internals, kanidmd

#1964 Fighting with zypper, tagging our images
  Makefile
  examples/apache_oauth/Dockerfile
  rlm_python/Dockerfile
  scripts/zypper_fixing.sh
  server/Dockerfile
  tools/Dockerfile
Labels: enhancement

#1971 Struct-ifying schema things
  server/lib/Cargo.toml
  server/lib/build.rs
  server/lib/src/constants/schema.rs
  server/lib/src/constants/uuids.rs
  server/lib/src/schema.rs
  server/lib/src/server/migrations.rs
  server/testkit/tests/integration.rs
Labels: rust, kanidmd

#1960 error handling and web server logging fixes
  libs/client/src/lib.rs
  libs/profiles/build.rs
  proto/src/v1.rs
  scripts/setup_dev_environment.sh
  scripts/zypper_fixing.sh
  server/core/src/actors/v1_read.rs
  server/core/src/https/middleware/mod.rs
  server/core/src/https/mod.rs
  server/core/src/https/trace.rs
  server/core/src/https/v1.rs
  server/testkit/src/lib.rs
  server/testkit/tests/default_entries.rs
  server/testkit/tests/http_manifest.rs
  server/testkit/tests/https_middleware.rs
  server/testkit/tests/integration.rs
  server/testkit/tests/oauth2_test.rs
  server/testkit/tests/person.rs
  server/testkit/tests/proto_v1_test.rs
  server/testkit/tests/scim_test.rs
  server/testkit/tests/self.rs
  server/testkit/tests/service_account.rs
  server/testkit/tests/system.rs
  server/testkit/tests/unix.rs
  tools/cli/src/cli/person.rs
  unix_integration/src/db.rs
Labels: uwu, kanidmd

#1988 sqlite - where IN for id entry
  Cargo.toml
  server/lib/Cargo.toml
  server/lib/src/be/idl_sqlite.rs
  unix_integration/Cargo.toml
Labels: uwu, internals, kanidmd

#1999 reordering layers so the web server works in non-debug-mode
  server/core/src/https/mod.rs
Labels: bug, kanidmd

#2018 docs: Update missed add_members command
  CONTRIBUTORS.md
  book/src/integrations/radius.md
Labels: documentation

#2017 feat: add json output modes for `person list` and `system oauth2 list`
  tools/cli/src/cli/oauth2.rs
  tools/cli/src/cli/person.rs
Labels: enhancement, kanidm (cli)

#2016 fix: output an array in json mode for `kanidm group list`
  tools/cli/src/cli/group.rs
Labels: enhancement, kanidm (cli)

#1965 Configurable session timeouts
  Cargo.lock
  libs/client/src/lib.rs
  libs/client/src/system.rs
  proto/src/constants.rs
  server/core/src/https/v1.rs
  server/daemon/src/main.rs
  server/lib/src/constants/acp.rs
  server/lib/src/constants/entries.rs
  server/lib/src/constants/mod.rs
  server/lib/src/constants/schema.rs
  server/lib/src/constants/system_config.rs
  server/lib/src/constants/uuids.rs
  server/lib/src/idm/account.rs
  server/lib/src/idm/authsession.rs
  server/lib/src/idm/credupdatesession.rs
  server/lib/src/idm/oauth2.rs
  server/lib/src/idm/server.rs
  server/lib/src/plugins/protected.rs
  server/lib/src/server/migrations.rs
  server/lib/src/server/mod.rs
  server/testkit/tests/default_entries.rs
  server/testkit/tests/proto_v1_test.rs
  tools/cli/src/cli/lib.rs
  tools/cli/src/cli/session_expiry.rs
  tools/cli/src/opt/kanidm.rs
Labels: enhancement, internals, kanidmd

#2021 Trying to fix the (current) container build failures
  rlm_python/Dockerfile
  tools/Dockerfile
Labels: bug, automation

#2001 idv cli
  Cargo.lock
  book/src/developers/designs/diagrams/idv_api_diagram.drawio
  book/src/developers/designs/diagrams/idv_api_diagram.drawio.svg
  book/src/developers/designs/diagrams/idv_generic_responses.drawio
  book/src/developers/designs/diagrams/idv_generic_responses.drawio.svg
  book/src/developers/designs/diagrams/idv_state_machine.drawio
  book/src/developers/designs/diagrams/idv_state_machine.drawio.svg
  book/src/developers/designs/identity_verification_feature.md
  server/web_ui/pkg/kanidmd_web_ui.js
  server/web_ui/pkg/kanidmd_web_ui_bg.wasm
  server/web_ui/pkg/kanidmd_web_ui_bg.wasm.br
  server/web_ui/src/views/identityverification.rs
  tools/cli/Cargo.toml
  tools/cli/src/cli/identify_user_tui.rs
  tools/cli/src/cli/lib.rs
  tools/cli/src/opt/kanidm.rs
Labels: enhancement, internals, kanidm (cli), kanidmd, api

#1993 Authentication shortcut to get a RW session
  libs/client/src/lib.rs
  proto/src/v1.rs
  server/lib/src/idm/authsession.rs
  server/lib/src/idm/event.rs
  server/lib/src/idm/server.rs
  server/testkit/tests/proto_v1_test.rs
  server/web_ui/src/login/mod.rs
Labels: api

#2043 Update compact jwt
  Cargo.lock
  Cargo.toml
Labels: bug

#1957 Add tests for X-Forwarded-For header (kinda)
  server/core/src/https/v1.rs
  server/testkit/tests/https_extractors.rs
Labels: enhancement, api
