Repository kanidm/kanidm, pull requests merged in 2023-07, with the labels that each got.

#1795 clippy-izing an unsafe in pam
  server/lib/src/entry.rs
  server/lib/src/lib.rs
  server/lib/src/repl/consumer.rs
  server/lib/src/valueset/session.rs
  unix_integration/pam_kanidm/src/pam/module.rs
Labels: rust

#1807 Add cors policy
  server/core/src/https/oauth2.rs
Labels: enhancement, oauth2

#1791 Add client UX for redirecting to an external portal for synced accounts
  libs/client/src/sync_account.rs
  proto/src/internal.rs
  proto/src/v1.rs
  server/core/src/https/v1_scim.rs
  server/lib/src/be/dbvalue.rs
  server/lib/src/constants/acp.rs
  server/lib/src/constants/schema.rs
  server/lib/src/constants/uuids.rs
  server/lib/src/constants/values.rs
  server/lib/src/idm/account.rs
  server/lib/src/idm/credupdatesession.rs
  server/lib/src/idm/scim.rs
  server/lib/src/idm/server.rs
  server/lib/src/repl/proto.rs
  server/lib/src/server/access/mod.rs
  server/lib/src/server/access/search.rs
  server/lib/src/server/migrations.rs
  server/lib/src/value.rs
  server/lib/src/valueset/cred.rs
  server/testkit/tests/scim_test.rs
  server/web_ui/Cargo.toml
  server/web_ui/pkg/kanidmd_web_ui.js
  server/web_ui/pkg/kanidmd_web_ui_bg.wasm
  server/web_ui/src/credential/reset.rs
  server/web_ui/src/views/mod.rs
  server/web_ui/src/views/profile.rs
  tools/cli/Cargo.toml
  tools/cli/build.rs
  tools/cli/src/cli/lib.rs
  tools/cli/src/cli/person.rs
  tools/cli/src/cli/synch.rs
  tools/cli/src/opt/kanidm.rs
Labels: enhancement

#1831 Allow Authorization header in CORS preflight response
  server/core/src/https/oauth2.rs
Labels: rust, kanidmd

#1844 headless webdriver testing, starting on brotli feature
  .github/workflows/kanidm_book.yml
  .github/workflows/wasm_test.yml
  .yamllint
  Cargo.lock
  server/core/src/https/oauth2.rs
  server/lib/src/idm/oauth2.rs
  server/testkit/Cargo.toml
  server/testkit/src/lib.rs
  server/testkit/tests/default_entries.rs
  server/testkit/tests/integration.rs
  server/web_ui/Cargo.toml
  server/web_ui/build_wasm.sh
  server/web_ui/find_best_brotli.sh
  server/web_ui/pkg/kanidmd_web_ui.js
  server/web_ui/pkg/kanidmd_web_ui_bg.wasm
  server/web_ui/pkg/kanidmd_web_ui_bg.wasm.br
  server/web_ui/src/login/mod.rs
  server/web_ui/tests/test.rs
Labels: enhancement, uwu, rust, automation

#1885 fixing up pydantic things
  pykanidm/kanidm/__init__.py
  pykanidm/kanidm/radius/__init__.py
  pykanidm/kanidm/tokens.py
  pykanidm/kanidm/types.py
  pykanidm/tests/test_authenticate.py
  pykanidm/tests/test_config_loader.py
  pykanidm/tests/test_jwt.py
  pykanidm/tests/test_radius_config.py
  pykanidm/tests/test_types.py
Labels: python

#1910 chasing weirdness
  .github/workflows/windows_build.yml
  book/src/DEVELOPER_README.md
  server/core/src/https/middleware/csp_headers.rs
  server/core/src/https/middleware/mod.rs
  server/core/src/https/middleware/security_headers.rs
  server/core/src/https/mod.rs
  server/core/src/https/v1.rs
  server/lib/src/idm/event.rs
  tools/cli/src/cli/common.rs
Labels: security, uwu, rust
