Repository kanidm/kanidm, pull requests merged in 2023-11, with the labels that each got.

#2283 Feature: configurable replication poll interval
  server/core/src/config.rs
  server/core/src/repl/mod.rs
  server/testkit/tests/mtls_test.rs
Labels: enhancement, kanidmd

#2285 Feature: kanidm CLI pulling OpenAPI schema
  book/src/developers/designs/rest_interface.md
  libs/client/src/lib.rs
  server/core/src/https/apidocs/mod.rs
  server/daemon/src/main.rs
  server/testkit/tests/integration.rs
  tools/cli/src/cli/lib.rs
  tools/cli/src/cli/main.rs
  tools/cli/src/cli/system_config/api.rs
  tools/cli/src/cli/system_config/mod.rs
  tools/cli/src/opt/kanidm.rs
Labels: documentation, kanidm (cli), api

#2290 OAuth2 Typo
  server/lib/src/idm/server.rs
  server/lib/src/server/mod.rs
Labels: kanidmd

#2291 WASM troubleshooting docs
  book/src/developers/designs/rest_interface.md
  book/src/developers/faq.md
  project_docs/RELEASE_CHECKLIST.md
Labels: documentation

#2296 Update OpenAPI schema gen to actually... be kinda sorta valid.
  Cargo.lock
  proto/src/internal.rs
  proto/src/scim_v1.rs
  proto/src/v1.rs
  scripts/openapi_tests/check_openapi_spec.sh
  server/core/Cargo.toml
  server/core/src/https/apidocs/mod.rs
  server/core/src/https/apidocs/path_schema.rs
  server/core/src/https/apidocs/response_schema.rs
  server/core/src/https/oauth2.rs
  server/core/src/https/v1.rs
  server/core/src/https/v1_oauth2.rs
  server/core/src/https/v1_scim.rs
  server/testkit/Cargo.toml
  server/testkit/tests/apidocs.rs
  tools/cli/src/cli/system_config/api.rs
Labels: documentation, api

#2297 Docs fixes for #2296
  book/src/DEVELOPER_README.md
  book/src/account_policy.md
  scripts/openapi_tests/check_openapi_spec.sh
Labels: documentation

#2292 Moving daemon tracing to OpenTelemetry
  Cargo.lock
  Cargo.toml
  Makefile
  book/src/developers/designs/logging.md
  book/src/developers/designs/logging.rst
  book/src/monitoring.md
  book/src/troubleshooting.md
  examples/insecure_server.toml
  libs/profiles/build.rs
  libs/sketching/Cargo.toml
  libs/sketching/src/lib.rs
  libs/sketching/src/macros.rs
  libs/sketching/src/otel.rs
  scripts/otel/README.md
  scripts/otel/docker-compose.yml
  scripts/otel/grafana-datasources.yaml
  scripts/otel/loki-local-config.yaml
  scripts/otel/multi_curl.sh
  scripts/otel/prometheus.yml
  scripts/otel/startup.sh
  scripts/otel/tempo.yaml
  server/core/src/actors/v1_write.rs
  server/core/src/config.rs
  server/core/src/https/mod.rs
  server/core/src/https/trace.rs
  server/daemon/Cargo.toml
  server/daemon/src/main.rs
  server/lib/src/constants/groups.rs
  server/lib/src/plugins/domain.rs
  server/lib/src/server/migrations.rs
  server/lib/src/server/recycle.rs
  server/lib/src/status.rs
  server/web_ui/admin/Cargo.toml
  server/web_ui/admin/pkg/kanidmd_web_ui_admin_bg.wasm
  server/web_ui/login_flows/Cargo.toml
  server/web_ui/login_flows/pkg/kanidmd_web_ui_login_flows_bg.wasm
  server/web_ui/pkg/external/bootstrap.bundle.min.js.br
  server/web_ui/pkg/external/bootstrap.bundle.min.js.map.br
  server/web_ui/pkg/external/bootstrap.min.css.map.br
  server/web_ui/pkg/img/icon-accounts.svg.br
  server/web_ui/pkg/img/icon-groups.svg.br
  server/web_ui/pkg/kanidmd_web_ui_admin.js.br
  server/web_ui/pkg/kanidmd_web_ui_admin_bg.wasm
  server/web_ui/pkg/kanidmd_web_ui_admin_bg.wasm.br
  server/web_ui/pkg/kanidmd_web_ui_login_flows_bg.wasm
  server/web_ui/pkg/kanidmd_web_ui_login_flows_bg.wasm.br
  server/web_ui/pkg/kanidmd_web_ui_user.js
  server/web_ui/pkg/kanidmd_web_ui_user.js.br
  server/web_ui/pkg/kanidmd_web_ui_user_bg.wasm
  server/web_ui/pkg/kanidmd_web_ui_user_bg.wasm.br
  server/web_ui/user/Cargo.toml
  server/web_ui/user/pkg/kanidmd_web_ui_user.js
  server/web_ui/user/pkg/kanidmd_web_ui_user_bg.wasm
Labels: kanidmd

#2309 Bump Fedora 36 to Fedora 38
  book/src/installing_client_tools.md
Labels: documentation

#2317 OAuth2 scopes validation logging missing details
  .gitignore
  server/lib/src/idm/credupdatesession.rs
  server/lib/src/idm/oauth2.rs
Labels: uwu

#2330 Better errors when TPM PINs not found
  unix_integration/src/daemon.rs
Labels: uwu

#2329 Adding env var configs for the server
  .gitignore
  examples/insecure_server.toml
  libs/sketching/src/otel.rs
  proto/src/constants.rs
  server/core/src/config.rs
  server/core/src/interval.rs
  server/core/src/lib.rs
  server/core/src/repl/config.rs
  server/core/src/repl/mod.rs
  server/daemon/src/main.rs
  server/lib/src/filter.rs
Labels: enhancement, kanidmd

#2333 Adding kanidm client config docs and notes
  book/src/client_tools.md
  book/src/installing_client_tools.md
  libs/client/src/lib.rs
  unix_integration/src/daemon.rs
Labels: uwu, documentation

#2348 Using proper axum http headers lib for compatibility
  server/core/src/https/errors.rs
  server/core/src/https/generic.rs
  server/core/src/https/manifest.rs
  server/core/src/https/middleware/caching.rs
  server/core/src/https/middleware/hsts_header.rs
  server/core/src/https/middleware/mod.rs
  server/core/src/https/middleware/security_headers.rs
  server/core/src/https/mod.rs
  server/core/src/https/oauth2.rs
  server/core/src/https/trace.rs
  server/core/src/https/ui.rs
  server/core/src/https/v1.rs
  server/lib/src/idm/oauth2.rs
Labels: enhancement
