Repository kanidm/kanidm, pull requests merged in 2024-11, with the labels that each got.

#3182 security - low - fault in migrations
  server/lib/src/entry.rs
  server/lib/src/server/access/mod.rs
  server/lib/src/server/modify.rs
Labels: security

#3245 owncloud: Add SameSite=Lax config for cross-domain auth
  book/src/integrations/oauth2/examples.md
Labels: documentation

#3242 handle missing map_group setting in config
  unix_integration/resolver/src/unix_config.rs
Labels: bug
