Repository kanidm/kanidm, pull requests merged in 2024-03, with the labels that each got.

#2590 OpenAPI schema fixes
  proto/src/internal/mod.rs
  scripts/openapi_tests/check_openapi_spec.sh
  scripts/test_run_release_server.sh
  server/core/src/https/apidocs/mod.rs
  server/core/src/https/generic.rs
  server/core/src/https/oauth2.rs
  server/core/src/https/v1.rs
  server/core/src/https/v1_oauth2.rs
  server/core/src/https/v1_scim.rs
Labels: documentation, api

#2609 SPAs really are stupid sometimes
  server/web_ui/admin/src/components/admin_accounts.rs
  server/web_ui/admin/src/components/admin_groups.rs
  server/web_ui/admin/src/components/admin_menu.rs
  server/web_ui/admin/src/components/admin_oauth2.rs
  server/web_ui/admin/src/components/admin_objectgraph.rs
  server/web_ui/admin/src/router.rs
  server/web_ui/pkg/external/bootstrap.bundle.min.js.map.br
  server/web_ui/pkg/external/bootstrap.min.css.map.br
  server/web_ui/pkg/external/viz.js.br
  server/web_ui/pkg/img/icon-accounts.svg.br
  server/web_ui/pkg/img/icon-groups.svg.br
  server/web_ui/pkg/kanidmd_web_ui_admin.js
  server/web_ui/pkg/kanidmd_web_ui_admin.js.br
  server/web_ui/pkg/kanidmd_web_ui_admin_bg.wasm
  server/web_ui/pkg/kanidmd_web_ui_admin_bg.wasm.br
  server/web_ui/pkg/kanidmd_web_ui_login_flows.js
  server/web_ui/pkg/kanidmd_web_ui_login_flows.js.br
  server/web_ui/pkg/kanidmd_web_ui_login_flows_bg.wasm
  server/web_ui/pkg/kanidmd_web_ui_login_flows_bg.wasm.br
  server/web_ui/pkg/kanidmd_web_ui_user.js
  server/web_ui/pkg/kanidmd_web_ui_user.js.br
  server/web_ui/pkg/kanidmd_web_ui_user_bg.wasm
  server/web_ui/pkg/kanidmd_web_ui_user_bg.wasm.br
Labels: enhancement

#2603 Adding a builtin class for all built-in things
  book/src/monitoring.md
  proto/src/constants.rs
  server/lib-macros/src/entry.rs
  server/lib/benches/scaling_10k.rs
  server/lib/src/constants/acp.rs
  server/lib/src/constants/entries.rs
  server/lib/src/constants/groups.rs
  server/lib/src/constants/uuids.rs
  server/lib/src/plugins/base.rs
  server/lib/src/schema.rs
  server/lib/src/server/migrations.rs
  server/lib/src/value.rs
  server/lib/src/valueset/uuid.rs
  server/testkit/tests/integration.rs
Labels: internals

#2602 20240301 systemd uid
  book/src/accounts/posix.md
  libs/client/src/group.rs
  proto/src/internal/error.rs
  proto/src/internal/mod.rs
  server/core/src/actors/internal.rs
  server/core/src/actors/mod.rs
  server/core/src/actors/v1_read.rs
  server/core/src/actors/v1_scim.rs
  server/core/src/actors/v1_write.rs
  server/core/src/admin.rs
  server/core/src/https/mod.rs
  server/core/src/interval.rs
  server/core/src/ldaps.rs
  server/core/src/lib.rs
  server/daemon/src/main.rs
  server/daemon/src/opt.rs
  server/lib/src/constants/mod.rs
  server/lib/src/entry.rs
  server/lib/src/idm/ldap.rs
  server/lib/src/lib.rs
  server/lib/src/plugins/gidnumber.rs
  server/lib/src/plugins/mod.rs
  server/lib/src/server/migrations.rs
  server/lib/src/server/mod.rs
  server/testkit/tests/proto_v1_test.rs
  tools/cli/src/cli/domain/mod.rs
  tools/cli/src/cli/group/mod.rs
  tools/cli/src/cli/person.rs
  tools/cli/src/cli/serviceaccount.rs
  tools/cli/src/opt/kanidm.rs
Labels: blocked, internals

#2674 Fix developer ethics link in README
  README.md
Labels: documentation

#2676 ldap-sync: allow to use attrs more than once
  Cargo.lock
  Cargo.toml
  tools/iam_migrations/ldap/src/main.rs
Labels: enhancement
