Repository kanidm/kanidm, pull requests merged in 2024-06, with the labels that each got.

#2809 v1.2.3 backport db path environment variable fix
  Cargo.lock
  Cargo.toml
  server/core/src/config.rs
Labels: bug

#2608 Better WebAuthn and other error responses
  libs/client/src/lib.rs
  proto/Cargo.toml
  proto/src/internal/error.rs
  scripts/setup_dev_environment.sh
  server/core/src/https/apidocs/mod.rs
  server/core/src/https/apidocs/response_schema.rs
  server/core/src/https/errors.rs
  server/lib/src/idm/credupdatesession.rs
  server/testkit/tests/integration.rs
  server/web_ui/pkg/external/bootstrap.bundle.min.js.br
  server/web_ui/pkg/external/bootstrap.bundle.min.js.map.br
  server/web_ui/pkg/external/bootstrap.min.css.br
  server/web_ui/pkg/external/bootstrap.min.css.map.br
  server/web_ui/pkg/external/viz.js.br
  server/web_ui/pkg/img/icon-accounts.svg.br
  server/web_ui/pkg/img/icon-groups.svg.br
  server/web_ui/pkg/kanidmd_web_ui_admin.js
  server/web_ui/pkg/kanidmd_web_ui_admin.js.br
  server/web_ui/pkg/kanidmd_web_ui_admin_bg.wasm
  server/web_ui/pkg/kanidmd_web_ui_admin_bg.wasm.br
  server/web_ui/pkg/kanidmd_web_ui_login_flows.js
  server/web_ui/pkg/kanidmd_web_ui_login_flows.js.br
  server/web_ui/pkg/kanidmd_web_ui_login_flows_bg.wasm
  server/web_ui/pkg/kanidmd_web_ui_login_flows_bg.wasm.br
  server/web_ui/pkg/kanidmd_web_ui_user.js
  server/web_ui/pkg/kanidmd_web_ui_user.js.br
  server/web_ui/pkg/kanidmd_web_ui_user_bg.wasm
  server/web_ui/pkg/kanidmd_web_ui_user_bg.wasm.br
  tools/cli/src/cli/raw.rs
Labels: enhancement, uwu

#2823 Remove small ambiguity in docs
  book/src/accounts/people_accounts.md
Labels: documentation

#2828 Shutting down the logging pipeline twice is a bit overkill 😄
  server/core/src/https/mod.rs
Labels: bug

#2827 fix: typos in OpenApi
  CONTRIBUTORS.md
  server/core/src/https/v1.rs
  server/web_ui/user/src/components/create_reset_code.rs
Labels: bug
