Repository kanidm/kanidm, pull requests merged in 2024-10, with the labels that each got.

#3085 Recommend Rust developers unlink Homebrew Rust on macOS
  book/src/installing_client_tools.md
Labels: documentation

#3076 Add example Outline config
  book/src/integrations/oauth2/examples.md
Labels: documentation

#3055 Fix landing and redirect URLs for GitLab, add some useful links
  book/src/integrations/oauth2/examples.md
Labels: documentation

#3096 fix(http): status content type should be JSON
  examples/kanidm
  libs/client/src/lib.rs
  server/core/src/https/generic.rs
Labels: uwu, api

#3091 Cache buster buster
  Cargo.lock
  libs/profiles/Cargo.toml
  libs/profiles/src/lib.rs
  libs/sketching/src/otel.rs
  scripts/setup_dev_environment.sh
  server/core/src/config.rs
  server/core/src/https/cache_buster.rs
  server/core/src/https/javascript.rs
  server/core/src/https/mod.rs
  server/core/src/https/ui.rs
  server/core/src/https/ui_html.html
  server/core/src/lib.rs
  server/core/src/repl/mod.rs
  server/core/templates/apps_partial.html
  server/core/templates/base.html
  server/core/templates/base_htmx.html
  server/core/templates/base_icons.html
  server/core/templates/credentials_reset_form.html
  server/core/templates/credentials_update_partial.html
  server/core/templates/login_base.html
  server/core/templates/login_webauthn.html
  server/core/templates/navbar.html
  server/core/templates/recoverable_error_partial.html
  server/core/templates/signout_modal.html
  server/core/templates/user_settings_partial_base.html
  server/testkit/tests/apidocs.rs
Labels: uwu

#3083 Improve deb packaging, add aarch64
  .github/workflows/debian_package_kanidm.yml
  .gitmodules
  book/src/integrations/pam_and_nsswitch.md
  book/src/packaging/debian_ubuntu_packaging.md
  book/src/packaging/ppa_packages.md
  examples/kanidm-safe-default
  examples/unixd-safe-default
  platform/crossbuild/README.md
  platform/crossbuild/build.sh
  platform/crossbuild/ubuntu-20.04/Cross.toml
  platform/crossbuild/ubuntu-20.04/Dockerfile
  platform/crossbuild/ubuntu-22.04/Cross.toml
  platform/crossbuild/ubuntu-22.04/Dockerfile
  platform/debian/Makefile
  platform/debian/README.md
  platform/debian/build_kanidm.sh
  platform/debian/interactive_entrypoint.sh
  platform/debian/kanidm-unixd/control
  platform/debian/kanidm-unixd/postinst
  platform/debian/kanidm-unixd/rules
  platform/debian/kanidm/control
  platform/debian/kanidm/rules
  platform/debian/kanidmd/control
  platform/debian/kanidmd/postinst
  platform/debian/kanidmd/rules
  platform/debian/packaging/compat
  platform/debian/packaging/copyright
  platform/debian/packaging/postrm.ex
  platform/debian/packaging/preinst
  platform/debian/packaging/prerm.ex
  platform/debian/packaging/source/format
  platform/debian/packaging/templates/changelog
  platform/debian/packaging/watch.ex
  platform/debian/simple_pkg.sh
  platform/debian/ubuntu_docker_builder.sh
  scripts/install_ubuntu_dependencies.sh
  server/daemon/debian/daemon.kanidmd.service
  tools/cli/Cargo.toml
  tools/cli/debian/postinst
  unix_integration/nss_kanidm/Cargo.toml
  unix_integration/pam_kanidm/Cargo.toml
  unix_integration/pam_kanidm/debian/kanidm.pam
  unix_integration/resolver/Cargo.toml
  unix_integration/resolver/debian/kanidm_unix_int.kanidm-unixd-tasks.service
  unix_integration/resolver/debian/kanidm_unix_int.kanidm-unixd.service
  unix_integration/resolver/debian/postinst
  unix_integration/resolver/debian/prerm
Labels: uwu

#3118 minor lintyboi fix
  server/core/src/lib.rs
Labels: uwu

#3121 more errors for the people
  Cargo.lock
  proto/src/internal/error.rs
  unix_integration/common/Cargo.toml
  unix_integration/common/src/unix_proto.rs
  unix_integration/pam_kanidm/src/core.rs
  unix_integration/resolver/src/bin/kanidm-unix.rs
  unix_integration/resolver/src/bin/kanidm_unixd.rs
Labels: uwu, unix

#3129 Add missing schemas to get OpenAPI validation to pass.
  Cargo.lock
  Cargo.toml
  proto/Cargo.toml
  proto/src/attribute.rs
  proto/src/v1/unix.rs
  server/core/src/https/apidocs/mod.rs
  server/core/src/https/v1_scim.rs
Labels: api

#3139 2856 - use tags for containers on build
  .github/workflows/docker_build_kanidm.yml
  .github/workflows/docker_build_kanidmd.yml
  .github/workflows/docker_build_radiusd.yml
Labels: automation

#3098 OAuth2 Device flow
  .devcontainer/devcontainer.json
  Cargo.lock
  Cargo.toml
  book/src/SUMMARY.md
  book/src/developers/designs/oauth2_device_flow.md
  libs/client/src/oauth.rs
  proto/Cargo.toml
  proto/src/attribute.rs
  proto/src/constants.rs
  proto/src/constants/uri.rs
  proto/src/oauth2.rs
  server/core/Cargo.toml
  server/core/src/actors/v1_write.rs
  server/core/src/https/oauth2.rs
  server/core/src/https/views/mod.rs
  server/core/src/https/views/oauth2.rs
  server/core/src/https/views/profile.rs
  server/core/templates/oauth2_consent_request.html
  server/core/templates/oauth2_device_login.html
  server/lib/Cargo.toml
  server/lib/src/constants/acp.rs
  server/lib/src/constants/entries.rs
  server/lib/src/constants/mod.rs
  server/lib/src/constants/schema.rs
  server/lib/src/constants/uuids.rs
  server/lib/src/idm/oauth2.rs
  server/lib/src/schema.rs
  server/lib/src/server/migrations.rs
  server/lib/src/server/mod.rs
  server/testkit/Cargo.toml
  server/testkit/src/lib.rs
  server/testkit/tests/oauth2_device_flow.rs
  server/testkit/tests/oauth2_test.rs
  tools/cli/Cargo.toml
  tools/cli/src/cli/oauth2.rs
  tools/cli/src/opt/kanidm.rs
  tools/device_flow/Cargo.toml
  tools/device_flow/examples/device_flow.rs
  tools/device_flow/src/lib.rs
Labels: uwu, oauth2

#3146 ripping out some unused packages from cargo.toml's
  Cargo.lock
  Cargo.toml
  libs/crypto/build.rs
  libs/scim_proto/Cargo.toml
  proto/Cargo.toml
  server/core/Cargo.toml
  server/daemon/Cargo.toml
  server/lib/Cargo.toml
  server/testkit/Cargo.toml
  tools/cli/Cargo.toml
Labels: uwu

#3147 Rewrite "choosing a domain", add other considerations
  book/src/choosing_a_domain_name.md
Labels: documentation

#3161 More "choosing a domain" revision
  book/src/choosing_a_domain_name.md
Labels: documentation
