Repository kanidm/kanidm, pull requests merged in 2024-01, with the labels that each got.

#2424 Clean RUV
  server/lib/src/repl/ruv.rs
Labels: replication

#2400 Debian build fixes (also the book)
  .github/workflows/debian_package_kanidm.yml
  .github/workflows/docker_build_kanidmd.yml
  .github/workflows/kanidm_book.yml
  platform/debian/Makefile
  platform/debian/build_kanidm.sh
  platform/debian/kanidm-unixd/control
  scripts/install_ubuntu_dependencies.sh
  unix_integration/src/client_sync.rs
Labels: automation, documentation

#2416 Adding max_ber_size option in config for ldap sync
  Cargo.lock
  Cargo.toml
  tools/iam_migrations/ldap/src/config.rs
  tools/iam_migrations/ldap/src/main.rs
Labels: enhancement

#2301 PyKanidm updates and testing
  Cargo.lock
  examples/config_localhost
  libs/client/src/oauth.rs
  libs/client/src/person.rs
  libs/sketching/src/otel.rs
  platform/debian/simple_pkg.sh
  pykanidm/kanidm/__init__.py
  pykanidm/kanidm/models/__init__.py
  pykanidm/kanidm/models/group.py
  pykanidm/kanidm/models/oauth2_rs.py
  pykanidm/kanidm/models/person.py
  pykanidm/kanidm/models/service_account.py
  pykanidm/kanidm/types.py
  pykanidm/pyproject.toml
  pykanidm/radius_test_env.sh
  pykanidm/tests/test_authenticate.py
  pykanidm/tests/test_config_loader.py
  pykanidm/tests/test_oauth2.py
  pykanidm/tests/test_oauth2_checks.py
  pykanidm/tests/test_radius_config.py
  pykanidm/tests/test_radius_token.py
  pykanidm/tests/testutils.py
  scripts/pykanidm/README.md
  scripts/pykanidm/integration_test.py
  scripts/pykanidm/run.sh
  server/core/src/https/mod.rs
  server/daemon/Cargo.toml
  server/daemon/src/main.rs
Labels: python
