Repository kanidm/kanidm, pull requests merged in 2024-09, with the labels that each got.

#3018 fix(kanidm): don't allow empty string fields on CLI
  tools/cli/src/opt/kanidm.rs
Labels: kanidm (cli)

#3031 fix(docs): make it clearer that bearer auth is a thing
  book/src/developers/designs/authentication_flow.md
Labels: documentation

#3037 CLI image error nicening
  Cargo.lock
  Cargo.toml
  libs/scim_proto/Cargo.toml
  libs/scim_proto/src/filter.rs
  proto/Cargo.toml
  proto/src/internal/mod.rs
  tools/cli/Cargo.toml
  tools/cli/src/cli/domain/mod.rs
  tools/cli/src/cli/oauth2.rs
  tools/cli/src/opt/kanidm.rs
Labels: uwu

#3049 fix(doc): updating docker container ref
  .github/workflows/kanidm_individual_book.yml
  book/src/evaluation_quickstart.md
Labels: documentation

#3050 Document basic user auth for self-hosted GitLab with Kanidm
  book/src/integrations/oauth2/examples.md
Labels: documentation

#3058 Add example config for JetBrains Hub / YouTrack
  book/src/integrations/oauth2/examples.md
Labels: documentation

#3059 Add ownCloud example config
  book/src/integrations/oauth2/examples.md
Labels: documentation

#3064 scim_proto: fix incorrect language tag (de-DE)
  libs/scim_proto/src/user.rs
Labels: bug

#3062 reformat oauth2 URL list, highlight legacy bits
  book/src/frequently_asked_questions.md
  book/src/integrations/oauth2.md
Labels: documentation
