Repository kanidm/kanidm, pull requests merged in 2024-02, with the labels that each got.

#2465 Trying this again...
  .github/workflows/kanidm_book.yml
Labels: automation, documentation

#2508 Ordering auth methods in the CLI
  proto/src/v1.rs
  tools/cli/src/cli/session.rs
Labels: enhancement, kanidm (cli)

#2546 When the HTTPS server fails, handle that gracefully, and check client_ca on startup 😄
  scripts/test_run_release_server.sh
  server/core/src/https/mod.rs
  server/core/src/lib.rs
  server/daemon/src/main.rs
Labels: kanidmd

#2547 fixing the test script
  scripts/test_run_release_server.sh
Labels: automation

#2556 Removing unused constant and updating docstring for LDAP bind address
  proto/src/constants.rs
  server/core/src/config.rs
  server/daemon/src/main.rs
  unix_integration/src/daemon.rs
Labels: documentation

#2558 prctl compile-time fixes, also chasing lints
  .github/workflows/clippy.yml
  clippy.toml
  libs/crypto/src/lib.rs
  libs/file_permissions/src/unix.rs
  scripts/install_ubuntu_dependencies.sh
  scripts/setup_dev_environment.sh
  server/lib/src/be/mod.rs
  server/lib/src/entry.rs
  server/lib/src/idm/applinks.rs
  server/lib/src/idm/credupdatesession.rs
  server/lib/src/idm/oauth2.rs
  server/lib/src/idm/scim.rs
  server/lib/src/plugins/session.rs
  server/lib/src/repl/entry.rs
  server/lib/src/value.rs
  server/lib/src/valueset/image/jpg.rs
  server/web_ui/individual_build.sh
  server/web_ui/pkg/external/bootstrap.bundle.min.js.br
  server/web_ui/pkg/external/bootstrap.bundle.min.js.map.br
  server/web_ui/pkg/external/bootstrap.min.css.map.br
  server/web_ui/pkg/img/icon-accounts.svg.br
  server/web_ui/pkg/img/icon-groups.svg.br
  server/web_ui/pkg/kanidmd_web_ui_admin.js
  server/web_ui/pkg/kanidmd_web_ui_admin.js.br
  server/web_ui/pkg/kanidmd_web_ui_admin_bg.wasm
  server/web_ui/pkg/kanidmd_web_ui_admin_bg.wasm.br
  server/web_ui/pkg/kanidmd_web_ui_login_flows.js
  server/web_ui/pkg/kanidmd_web_ui_login_flows.js.br
  server/web_ui/pkg/kanidmd_web_ui_login_flows_bg.wasm
  server/web_ui/pkg/kanidmd_web_ui_login_flows_bg.wasm.br
  server/web_ui/pkg/kanidmd_web_ui_user.js
  server/web_ui/pkg/kanidmd_web_ui_user.js.br
  server/web_ui/pkg/kanidmd_web_ui_user_bg.wasm
  server/web_ui/pkg/kanidmd_web_ui_user_bg.wasm.br
  server/web_ui/user/src/credential/reset.rs
  tools/orca/src/main.rs
  unix_integration/src/daemon.rs
  unix_integration/src/db.rs
  unix_integration/src/tasks_daemon.rs
  unix_integration/src/unix_passwd.rs
  unix_integration/tests/cache_layer_test.rs
Labels: uwu, automation

#2550 Adding duplicate-finder script
  scripts/find_duplicated_names.sh
Labels: automation, documentation

#2560 I started looking at clippy things and now I can't stop
  libs/client/src/lib.rs
  libs/crypto/src/lib.rs
  server/core/src/crypto.rs
  server/core/src/https/apidocs/tests.rs
  server/lib/src/be/idl_sqlite.rs
  server/lib/src/be/mod.rs
  server/lib/src/idm/credupdatesession.rs
  server/lib/src/idm/oauth2.rs
  server/lib/src/idm/server.rs
  server/lib/src/macros.rs
  server/lib/src/plugins/session.rs
  server/lib/src/repl/entry.rs
  server/lib/src/repl/tests.rs
  server/lib/src/schema.rs
  server/lib/src/server/recycle.rs
  server/lib/src/valueset/address.rs
  server/lib/src/valueset/image/png.rs
  server/testkit/examples/enumerating_access.rs
  server/testkit/tests/apidocs.rs
  server/testkit/tests/oauth2_test.rs
  server/testkit/tests/proto_v1_test.rs
  tools/iam_migrations/freeipa/src/tests.rs
  tools/iam_migrations/ldap/src/main.rs
  unix_integration/src/selinux_util.rs
Labels: uwu

#2582 Changing to allow startup without a config file
  Cargo.lock
  Makefile
  book/src/accounts/policy.md
  book/src/server_configuration.md
  scripts/setup_dev_environment.sh
  scripts/test_run_release_server.sh
  server/core/src/config.rs
  server/daemon/Cargo.toml
  server/daemon/src/main.rs
  server/daemon/src/opt.rs
  server/lib/src/idm/server.rs
  tools/iam_migrations/freeipa/src/main.rs
Labels: enhancement, kanidmd

#2594 docs(monitoring): Fix syntax for OpenTelemetry config
  book/src/monitoring.md
Labels: documentation

#2595 WASM test fixing
  .github/workflows/wasm_test.yml
  Makefile
  server/web_ui/shared/tests/test.rs
Labels: automation
