Repository kanidm/kanidm, pull requests merged in 2025-01, with the labels that each got.

#3329 Javascript linting
  .editorconfig
  .github/workflows/javascript_lint.yml
  .gitignore
  Makefile
  server/core/eslint.config.mjs
  server/core/package-lock.json
  server/core/package.json
  server/core/prettier-ignore
  server/core/static/modules/cred_update.mjs
  server/core/static/pkhtml.js
  server/core/static/style.css
Labels: automation

#3338 Renaming "TOTP" in the login flow
  server/core/templates/login_totp.html
Labels: uwu

#3352 fix: unrecoverable error page doesn't include logo or domain name
  server/core/Cargo.toml
  server/core/src/https/views/apps.rs
  server/core/src/https/views/enrol.rs
  server/core/src/https/views/errors.rs
  server/core/src/https/views/login.rs
  server/core/src/https/views/mod.rs
  server/core/src/https/views/oauth2.rs
  server/core/src/https/views/profile.rs
  server/core/src/https/views/reset.rs
  server/core/templates/unrecoverable_error.html
  server/lib/Cargo.toml
  server/lib/src/server/mod.rs
Labels: uwu

#3355 Repair systemd reload notifications
  .github/workflows/clippy.yml
  .github/workflows/rust_build.yml
  Cargo.lock
  Cargo.toml
  book/src/developers/readme.md
  scripts/devcontainer_postcreate.sh
  scripts/install_ubuntu_dependencies.sh
  server/Dockerfile
  server/daemon/src/main.rs
Labels: unix
